version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "2333:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./temp:/app/temp

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5556:5556"
    environment:
      - FRONTEND_URL=http://frontend:80  # Docker 网络中使用服务名访问
    restart: always
    volumes:
      - ./temp:/app/temp